# Generated by Django 5.1.3 on 2024-11-28 12:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('mssisdn', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('id_number', models.CharField(max_length=100, verbose_name='ID Number')),
                ('id_picture', models.CharField(max_length=200, verbose_name='Photo of ID')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('id_type', models.ForeignKey(blank=True, default=['Passport'], on_delete=django.db.models.deletion.CASCADE, to='customers.idtype', verbose_name='ID Type')),
                ('sim_type', models.ForeignKey(blank=True, default=['Passport'], on_delete=django.db.models.deletion.CASCADE, to='customers.simtype', verbose_name='Sim Type')),
            ],
        ),
    ]
