# Generated by Django 5.1.3 on 2024-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(choices=[('esim', 'Embedded Sim'), ('standard', 'Standard Sim')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sim_type',
            field=models.CharField(choices=[('esim', 'Embedded Sim'), ('standard', 'Standard Sim')], max_length=15),
        ),
    ]
