# Generated by Django 4.1.13 on 2024-11-05 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 13, 5, 33, 189805),
                verbose_name="Date Created",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id_type",
            field=models.ForeignKey(
                blank=True,
                default=["Passport"],
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.idtype",
                verbose_name="ID Type",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sim_type",
            field=models.ForeignKey(
                blank=True,
                default=["Passport"],
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.simtype",
                verbose_name="Sim Type",
            ),
        ),
    ]
