# Generated by Django 4.1.13 on 2024-11-05 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_date_created_alter_customer_id_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 13, 13, 3, 919142),
                verbose_name="Date Created",
            ),
        ),
    ]
