# Generated by Django 5.1.3 on 2024-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('voters_id', 'Voters ID'), ('license', 'License')], max_length=15),
        ),
    ]
