# Generated by Django 4.1.13 on 2024-11-05 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_alter_customer_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Created"
            ),
        ),
    ]
