# Generated by Django 5.1.3 on 2024-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(choices=[('nin', 'National ID'), ('pp', 'Passport'), ('vi', 'Voters ID'), ('lic', 'License')], max_length=15),
        ),
    ]
