# Generated by Django 5.1.3 on 2024-11-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_id_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDType',
        ),
        migrations.DeleteModel(
            name='SimType',
        ),
    ]
